#!/bin/bash
echo "🛠️Loading configuration";

MYSQL_USER="MYSQL_USER_NAME"
MYSQL_PASSWORD="MYSQL_USER_PASSWORD"
MYSQL_HOST="MYSQL_HOST"
WORDPRESS_BDD="MYSQL_DATABASE_NAME"
WORDPRESS_TABLE_PREFIX="wp_"
WORDPRESS_FOLDER="wp"
WORDPRES_URL="http://localhost/PAHT_TO_REPOSITORY/site/"

WORDPRES_SITE_NAME="SITE_NAME"
WORDPRES_ADMIN_NAME="WP_BO_ADMIN_LOGIN"
WORDPRES_ADMIN_PASSWORD="WP_BO_ADMIN_PASSWORD"
WORDPRES_ADMIN_EMAIL="WP_BO_ADMIN@EMAIL.COM"